<?php

$routes = static fn (string $permission, array $names): array => array_fill_keys($names, $permission);

return [
    /*
    |--------------------------------------------------------------------------
    | EBIMS Operational Permission Catalogue
    |--------------------------------------------------------------------------
    |
    | These permissions are shown in the access-control UI and are enforced by
    | EbimsPermissionAccess for mapped routes. Super administrators always
    | bypass operational checks.
    |
    */
    'catalog' => [
        'access-ebmis-modules' => [
            'group' => 'Workspace',
            'label' => 'Access EBIMS Modules',
            'description' => 'Open the EBIMS operational dashboard and modules.',
        ],
        'view-branch-dashboard' => [
            'group' => 'Workspace',
            'label' => 'View Branch Dashboard',
            'description' => 'View the main operational dashboard.',
        ],
        'view-active-loans' => [
            'group' => 'Loans',
            'label' => 'View Active Loans Across Branches',
            'description' => 'View and work with active loans from all branches.',
        ],
        'view-loan-details' => [
            'group' => 'Loans',
            'label' => 'View Loan Details',
            'description' => 'View loan records, schedules, statements, and notices.',
        ],
        'manage-loan-documents' => [
            'group' => 'Loans',
            'label' => 'Manage Loan Documents',
            'description' => 'Upload and remove loan supporting documents.',
        ],
        'manage-loan-guarantors' => [
            'group' => 'Loans',
            'label' => 'Manage Loan Guarantors',
            'description' => 'Add or remove guarantors attached to loans.',
        ],
        'manage-loan-agreements' => [
            'group' => 'Loans',
            'label' => 'Manage Loan Agreements',
            'description' => 'Prepare, sign, regenerate, and download loan agreements.',
        ],
        'collect-loan-fees' => [
            'group' => 'Collections',
            'label' => 'Collect Loan Fees',
            'description' => 'Initiate and monitor permitted loan-fee collections.',
        ],
        'record-mobile-money-repayment' => [
            'group' => 'Collections',
            'label' => 'Record Mobile Money Repayment',
            'description' => 'Initiate mobile-money repayments and monitor callback confirmation.',
        ],
        'restructure-loan' => [
            'group' => 'Loans',
            'label' => 'Restructure Loan',
            'description' => 'Restructure or reschedule an eligible loan.',
        ],
        'generate-loan-schedules' => [
            'group' => 'Loans',
            'label' => 'Generate Loan Schedules',
            'description' => 'Generate repayment schedules for eligible loans.',
        ],
        'manage-loan-charge-type' => [
            'group' => 'Loans',
            'label' => 'Manage Loan Charge Type',
            'description' => 'Change how approved loan charges are applied.',
        ],
        'manage-client-applications' => [
            'group' => 'Loans',
            'label' => 'Manage Client Applications',
            'description' => 'View self-service client loan applications.',
        ],
        'view-disbursements' => [
            'group' => 'Loans',
            'label' => 'View Disbursements',
            'description' => 'View pending and historical loan disbursements.',
        ],
        'manage-late-fees' => [
            'group' => 'Loans',
            'label' => 'View Late Fees',
            'description' => 'View late-fee records. Waiving fees remains restricted to super administrators.',
        ],
        'manage-cash-securities' => [
            'group' => 'Collateral',
            'label' => 'Manage Cash Securities',
            'description' => 'Record and view cash-security collateral transactions.',
        ],
        'manage-member-assessments' => [
            'group' => 'Clients',
            'label' => 'Manage Member Assessments',
            'description' => 'Maintain member businesses, assets, liabilities, and documents.',
        ],
        'manage-fees' => [
            'group' => 'Collections',
            'label' => 'Manage Fees',
            'description' => 'View and collect member or loan fees.',
        ],
        'view-accounting-reports' => [
            'group' => 'Accounting',
            'label' => 'View Accounting Reports',
            'description' => 'View accounting journals, statements, and the chart of accounts.',
        ],
        'view-umra-reports' => [
            'group' => 'Reporting',
            'label' => 'View UMRA Reports',
            'description' => 'View and export UMRA regulatory reports.',
        ],
        'manage-investments' => [
            'group' => 'Investments',
            'label' => 'Manage Investments',
            'description' => 'View and maintain investment records.',
        ],
        'manage-school-loans' => [
            'group' => 'School Loans',
            'label' => 'Manage School Loans',
            'description' => 'View and maintain school-loan records.',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Route Permission Mapping
    |--------------------------------------------------------------------------
    |
    | Every operational route is listed explicitly. Unmapped operational routes
    | are rejected by middleware until their permission is deliberately chosen.
    |
    */
    'route_permissions' => array_merge(
        $routes('view-branch-dashboard', [
            'admin.home',
            'admin.api.states',
            'admin.api.cities',
        ]),
        $routes('manage-client-applications', [
            'admin.client-applications.index',
            'admin.client-applications.show',
        ]),
        $routes('perform-field-verification', [
            'admin.client-applications.verify',
            'admin.client-applications.verify.submit',
        ]),
        $routes('approve-loan', ['admin.client-applications.approve']),
        $routes('reject-loan', ['admin.client-applications.reject']),
        $routes('view-client-details', [
            'admin.members.search',
            'admin.members.index',
            'admin.members.show',
            'admin.members.pending',
            'admin.members.details',
            'admin.members.check-duplicate',
            'admin.members.quick-info',
            'admin.members.loans',
            'admin.members.recent-fees',
        ]),
        $routes('add-client', ['admin.members.create', 'admin.members.store']),
        $routes('edit-client', [
            'admin.members.edit',
            'admin.members.update',
            'admin.members.approve',
            'admin.members.reject',
            'admin.members.suspend',
        ]),
        $routes('delete-client', ['admin.members.destroy']),
        $routes('manage-member-assessments', [
            'admin.members.businesses.index',
            'admin.members.businesses.create',
            'admin.members.businesses.store',
            'admin.members.businesses.edit',
            'admin.members.businesses.update',
            'admin.members.businesses.destroy',
            'admin.members.assets.store',
            'admin.members.assets.update',
            'admin.members.assets.destroy',
            'admin.members.liabilities.store',
            'admin.members.liabilities.update',
            'admin.members.liabilities.destroy',
            'admin.members.documents.store',
            'admin.members.documents.reupload',
            'admin.members.documents.download',
            'admin.members.documents.destroy',
        ]),
        $routes('manage-cash-securities', [
            'admin.cash-securities.store',
            'admin.cash-securities.return',
            'admin.cash-securities.check-status',
            'admin.cash-securities.show',
            'admin.cash-securities.receipt',
            'admin.cash-securities.destroy',
        ]),
        $routes('manage-school-loans', [
            'admin.school.loans.create',
            'admin.school.loans.store',
            'admin.school.loans.approvals',
            'admin.school.loans.disbursements',
            'admin.school.loans.active',
            'admin.school.loans.repayments',
            'admin.school.loans.portfolio',
        ]),
        $routes('manage-loans', [
            'admin.loans.approvals',
            'admin.loans.export',
            'admin.loans.rejected',
            'admin.loans.rejected.export',
            'admin.loans.index',
        ]),
        $routes('view-loan-details', [
            'admin.loans.show',
            'admin.loans.details',
            'admin.loans.personal.preview-dashboard',
            'admin.loans.next-schedule',
            'admin.loans.history',
            'admin.loans.statements.print',
            'admin.loans.schedules.print',
            'admin.loans.notices.print',
            'admin.loan-management.approve.show',
        ]),
        $routes('create-loan-application', [
            'admin.loans.create',
            'admin.loans.store',
            'admin.loans.calculate',
            'admin.loans.calculate-fees-service',
            'admin.loans.check-eligibility-service',
        ]),
        $routes('edit-loan-application', [
            'admin.loans.edit',
            'admin.loans.update',
        ]),
        $routes('approve-loan', [
            'admin.loans.approve',
            'admin.loan-management.approve',
        ]),
        $routes('reject-loan', [
            'admin.loans.reject',
            'admin.loan-management.reject',
        ]),
        $routes('view-active-loans', [
            'admin.loans.active',
            'admin.loans.active.export',
            'admin.loans.collateral.show',
        ]),
        $routes('record-loan-collateral', ['admin.loans.collateral.store']),
        $routes('record-loan-follow-up', ['admin.loans.follow-ups.store']),
        $routes('collect-loan-fees', [
            'admin.loans.pay-fees',
            'admin.loans.pay-single-fee',
            'admin.loans.store-mobile-money',
            'admin.loans.check-mm-status',
            'admin.loans.retry-mobile-money',
            'admin.loan-management.fees.show',
        ]),
        $routes('manage-loan-documents', [
            'admin.loans.upload-document',
            'admin.loans.delete-document',
        ]),
        $routes('manage-loan-guarantors', [
            'admin.loans.add-guarantor',
            'admin.loans.remove-guarantor',
        ]),
        $routes('manage-loan-charge-type', ['admin.loans.update-charge-type']),
        $routes('manage-loan-agreements', [
            'admin.loans.esign',
            'admin.loans.agreements',
            'admin.loans.send-otp',
            'admin.loans.sign-agreement',
            'admin.loans.view-agreement',
            'admin.loans.download-signed-agreement',
            'admin.loans.save-esignature',
            'admin.loans.regenerate-agreement',
            'admin.loans.save-guarantor-signature',
        ]),
        $routes('generate-loan-schedules', [
            'admin.loans.generate-schedule-service',
            'admin.loan-management.schedule.generate',
        ]),
        $routes('restructure-loan', [
            'admin.loans.reschedule',
            'admin.loans.restructure',
            'admin.loans.restructure.store',
        ]),
        $routes('view-disbursements', [
            'admin.loan-management.disbursements',
            'admin.disbursements.index',
            'admin.disbursements.show',
            'admin.disbursements.loan-details',
            'admin.loans.disbursements.pending',
            'admin.loans.disbursements.export',
        ]),
        $routes('view-repayment-history', [
            'admin.loan-management.repayments',
            'admin.repayments.index',
            'admin.repayments.show',
            'admin.repayments.pending',
            'admin.repayments.history',
            'admin.repayments.loan-details',
            'admin.repayments.receipt',
        ]),
        $routes('view-loan-schedule', [
            'admin.loan-management.schedule.show',
            'admin.loans.repayments.schedules',
            'admin.loans.repayments.get',
            'admin.loans.repayments.schedule-pending',
            'admin.loans.schedules.payments',
            'admin.loans.repayments.get-pending-transaction',
        ]),
        $routes('record-mobile-money-repayment', [
            'admin.loan-management.repayments.process',
            'admin.loans.repayments.quick',
            'admin.loans.repayments.store',
            'admin.loans.repayments.pay-balance',
            'admin.loans.repayments.store-mobile-money',
            'admin.loans.repayments.check-mm-status',
            'admin.loans.repayments.retry-mobile-money',
            'admin.check-payment-status',
        ]),
        $routes('manage-late-fees', ['admin.late-fees.index']),
        $routes('generate-loan-reports', [
            'admin.portfolio.running',
            'admin.portfolio.pending',
            'admin.portfolio.overdue',
            'admin.portfolio.paid',
            'admin.portfolio.bad',
            'admin.portfolio.branch',
            'admin.portfolio.product',
            'admin.portfolio.individual',
            'admin.portfolio.group',
            'admin.reports.pending-loans',
            'admin.reports.disbursed-loans',
            'admin.reports.rejected-loans',
            'admin.reports.loans-due',
            'admin.reports.paid-loans',
            'admin.reports.loan-repayments',
            'admin.reports.payment-transactions',
            'admin.reports.loan-interest',
            'admin.reports.cash-securities',
            'admin.reports.loan-charges',
        ]),
        $routes('send-sms-notifications', [
            'admin.bulk-sms.index',
            'admin.bulk-sms.create',
            'admin.bulk-sms.store',
            'admin.bulk-sms.show',
            'admin.bulk-sms.edit',
            'admin.bulk-sms.update',
            'admin.bulk-sms.destroy',
        ]),
        $routes('manage-group-members', [
            'admin.groups.index',
            'admin.groups.create',
            'admin.groups.store',
            'admin.groups.show',
            'admin.groups.edit',
            'admin.groups.update',
            'admin.groups.destroy',
            'admin.groups.approve',
            'admin.groups.suspend',
            'admin.groups.activate',
            'admin.groups.members',
            'admin.groups.add-member',
            'admin.groups.remove-member',
            'admin.groups.available-members',
            'admin.groups.loan-eligibility',
        ]),
        $routes('manage-fees', [
            'admin.fees.index',
            'admin.fees.create',
            'admin.fees.store',
            'admin.fees.show',
            'admin.fees.edit',
            'admin.fees.update',
            'admin.fees.destroy',
            'admin.fees.receipt',
            'admin.fees.receipt-modal',
            'admin.fees.store-mobile-money',
            'admin.fees.check-mm-status',
            'admin.fees.retry-mobile-money',
            'admin.fees.member.status',
            'admin.fees.loan.charges',
            'admin.fees.mobile-money',
            'admin.fees.mobile-money.status',
            'admin.fees.mobile-money.retry',
            'admin.fees.types.ajax',
            'admin.fees.members.search',
            'admin.fee-types.info',
        ]),
        $routes('manage-savings-accounts', [
            'admin.savings.index',
            'admin.savings.create',
            'admin.savings.store',
            'admin.savings.show',
            'admin.savings.edit',
            'admin.savings.update',
            'admin.savings.destroy',
            'admin.savings.pending',
            'admin.savings.approved',
            'admin.savings.approve',
            'admin.savings.reject',
            'admin.savings.check-payment-status',
        ]),
        $routes('manage-investments', [
            'admin.investments.index',
            'admin.investments.investors',
            'admin.investments.create-investor',
            'admin.investments.store-investor',
            'admin.investments.show-investor',
            'admin.investments.edit-investor',
            'admin.investments.update-investor',
            'admin.investments.activate-investor',
            'admin.investments.deactivate-investor',
            'admin.investments.delete-investor',
            'admin.investments.create-investment',
            'admin.investments.store-investment',
            'admin.investments.show-investment',
            'admin.investments.edit-investment',
            'admin.investments.update-investment',
            'admin.investments.destroy',
            'admin.investments.calculate-returns',
            'admin.investments.api.investor-portfolio',
            'admin.investments.api.investment-statistics',
        ]),
        $routes('view-accounting-reports', [
            'admin.accounting.journal-entries',
            'admin.accounting.journal-entries.download',
            'admin.accounting.journal-entry',
            'admin.accounting.trial-balance',
            'admin.accounting.trial-balance.download',
            'admin.accounting.balance-sheet',
            'admin.accounting.balance-sheet.download',
            'admin.accounting.income-statement',
            'admin.accounting.income-statement.download',
            'admin.accounting.chart-of-accounts',
            'admin.accounting.chart-of-accounts.download',
        ]),
        $routes('view-umra-reports', [
            'admin.umra.dashboard',
            'admin.umra.loan-preview',
            'admin.umra.loan-records',
            'admin.umra.collateral-register',
            'admin.umra.collateral-register.export',
            'admin.umra.collateral-register.pdf',
            'admin.umra.schedule3',
            'admin.umra.schedule3.export',
            'admin.umra.prudential-pack',
            'admin.umra.prudential-pack.export',
            'admin.umra.prudential-pack.pdf',
            'admin.umra.export-excel',
            'admin.umra.export-preview',
            'admin.umra.export-pdf',
        ]),
    ),

    /*
    |--------------------------------------------------------------------------
    | Super Administrator Financial Mutations
    |--------------------------------------------------------------------------
    |
    | The route audit verifies that these high-risk actions retain the
    | super_admin middleware even if their controllers are refactored.
    |
    */
    'sensitive_super_admin_routes' => [
        'admin.loans.destroy',
        'admin.loans.revert',
        'admin.loans.close-manual',
        'admin.loan-management.disbursements.process',
        'admin.disbursements.create',
        'admin.disbursements.store',
        'admin.disbursements.edit',
        'admin.disbursements.update',
        'admin.disbursements.destroy',
        'admin.disbursements.complete',
        'admin.disbursements.cancel',
        'admin.disbursements.retry',
        'admin.disbursements.approve.show',
        'admin.disbursements.approve',
        'admin.loans.disbursements.approve.show',
        'admin.loans.disbursements.approve',
        'admin.loans.disbursements.check-status',
        'admin.loans.stop',
        'admin.repayments.create',
        'admin.repayments.store',
        'admin.repayments.edit',
        'admin.repayments.update',
        'admin.repayments.destroy',
        'admin.late-fees.waive',
        'admin.late-fees.bulk-waive',
        'admin.late-fees.show-waive-upgrade',
        'admin.late-fees.waive-upgrade-period',
        'admin.loans.late-fees.waive',
        'admin.loans.carry-over',
        'admin.fees.mark-paid',
        'admin.loan-management.mobile-money.test',
    ],

    'public_application_routes' => [
        'cron.run',
        'csrf-token.refresh',
        'school.register',
        'school.register.store',
        'school.assessment',
        'school.assessment.store',
        'school.complete-assessment',
        'school.continue-assessment',
        'client.apply',
        'client.apply.store',
        'client.apply.success',
        'client.apply.check-status',
        'client.loan-status',
        'public.mobile-money.callback',
        'api.locations.districts',
        'api.locations.subcounties',
        'api.locations.parishes',
        'api.locations.villages',
        'api.locations.search',
    ],

    'throttled_public_routes' => [
        'cron.run',
        'csrf-token.refresh',
        'school.register.store',
        'school.assessment.store',
        'school.continue-assessment',
        'client.apply.store',
        'client.loan-status',
        'public.mobile-money.callback',
        'api.locations.districts',
        'api.locations.subcounties',
        'api.locations.parishes',
        'api.locations.villages',
        'api.locations.search',
    ],

    'authenticated_application_routes' => [
        'logout',
        'dashboard',
        'api.user',
    ],

    /*
    |--------------------------------------------------------------------------
    | Initial Role Defaults
    |--------------------------------------------------------------------------
    |
    | A deployment migration applies these once to existing operational roles.
    | Administrators can then refine them from the role editor.
    |
    */
    'default_roles' => [
        'Branch Manager' => [
            'access-ebmis-modules',
            'view-branch-dashboard',
            'view-active-loans',
            'view-assigned-loans',
            'view-loan-schedule',
            'view-loan-details',
            'manage-client-applications',
            'perform-field-verification',
            'view-own-clients',
            'view-client-details',
            'add-client',
            'edit-client',
            'delete-client',
            'manage-member-assessments',
            'create-loan-application',
            'edit-loan-application',
            'approve-loan',
            'reject-loan',
            'manage-loans',
            'manage-loan-documents',
            'manage-loan-guarantors',
            'manage-loan-agreements',
            'collect-loan-fees',
            'record-mobile-money-repayment',
            'restructure-loan',
            'generate-loan-schedules',
            'manage-loan-charge-type',
            'view-disbursements',
            'record-repayment',
            'view-repayment-history',
            'record-loan-follow-up',
            'record-loan-collateral',
            'manage-late-fees',
            'manage-cash-securities',
            'manage-fees',
            'manage-savings-accounts',
            'record-savings-deposit',
            'record-savings-withdrawal',
            'view-savings-reports',
            'create-group',
            'manage-group-members',
            'create-group-loan',
            'view-group-reports',
            'send-sms-notifications',
            'generate-loan-reports',
            'view-accounting-reports',
            'view-umra-reports',
            'manage-school-loans',
        ],
        'Loan Officer' => [
            'access-ebmis-modules',
            'view-branch-dashboard',
            'view-active-loans',
            'view-assigned-loans',
            'view-loan-schedule',
            'view-loan-details',
            'record-repayment',
            'record-mobile-money-repayment',
            'view-repayment-history',
            'perform-field-verification',
            'record-loan-follow-up',
            'record-loan-collateral',
            'view-umra-reports',
        ],
        'Field Officer' => [
            'access-ebmis-modules',
            'view-branch-dashboard',
            'view-active-loans',
            'view-assigned-loans',
            'view-loan-schedule',
            'view-loan-details',
            'record-repayment',
            'record-mobile-money-repayment',
            'view-repayment-history',
            'perform-field-verification',
            'record-loan-follow-up',
            'record-loan-collateral',
            'view-umra-reports',
        ],
    ],
];
